### ISSUE TITLE
Add a template with an HTML form and make the index view render it

### ISSUE THREAD

**Issue by infraredgirl** [mddemarie/travelator#2]
Create a template file (index.html) which should contain an HTML form.

> _big title text_ "Travelator"
> 
> I am a citizen of _select box_
> and I want to travel to _select box_
> 
> button with text "Do I need a visa?"
> 

Don't worry about populating the select boxes with list of countries yet, it can be done later. For now, just leave them empty.

Then make the index() view function in https://github.com/mddemarie/travelator/blob/master/visas/views.py render the above written template. (Hint: you should use Django's render() function to accomplish this. An example can be found here: https://docs.djangoproject.com/en/1.10/intro/tutorial03/#a-shortcut-render)

**Comment by mddemarie** [comment]
1. change the view in visas/views.py and mention in the code that you will use index.html template + use the render() function for this purpose as written above.
- really nice instuctions are also here: https://tutorial.djangogirls.org/en/django_views/

2. make the folder "templates" in the folder "visas", open the folder "templates" and create here a new folder "visas". Open this folder "visas" and create there a template file "index.html". In the file "index.html" there you write the HTML code with the above mentioned content + button. (You have to search how to write a button in HTML) The template file called index.html is meant for displaying the content on the front page of a website in Django. 
- more about templates in HTML here: https://tutorial.djangogirls.org/en/html/

3. run the server, make sure it works.

**Comment by infraredgirl** [comment]
Fixed in commit b6eeefb9e57873a9ab25b80994169e595d64f1ff.
